### ISSUE TITLE
editorconfig работает не корректно

### ISSUE THREAD

**Issue by NikolayLemehov** [dDenysS/gulp-template#11]
В editorconfig заявлено, что окончание строк должно быть [LF](http://prntscr.com/te4u7j), но по факту изменяя в папке src/styles стилевого файла style.scss на формат окончания строк CRLF editorconfig этого не видит, хотя если изменить в .editorconfig параметр indent_size с 2 на другой, то ошибки сыпятся.
Следующее [изменение](http://prntscr.com/te94vq) путей в package.json к файлам для проверки editorconfig решает эту задачу.
Вот [Pull request](https://github.com/dDenysS/gulp-template/pull/10) для решения этой задачи.

**Comment by dDenysS** [comment]
@NikolayLemehov Благодарю за исправление ошибок.
