### ISSUE TITLE
Сообщение от stylelint в scss.

### ISSUE THREAD

**Issue by NikolayLemehov** [dDenysS/gulp-template#12]
При открытии в phpstorm файла scss появляется [сообщение](http://prntscr.com/te9cft) stylelint в котором он просит запустить следующую команду npm update.
Не знаю есть ли необходимость обновлять репозиторий, но я бы обновил.
Скажите, пожалуйста, своё мнение.

**Comment by dDenysS** [comment]
@NikolayLemehov Спасибо. Да, стоит обновить зависимости.
