### ISSUE TITLE
Как подключить стили к отдельной странице/блоку?

### ISSUE THREAD

**Issue by yurii-martyniuk** [dDenysS/gulp-template#2]
Как подключить стили к отдельной странице/блоку?
![example](https://user-images.githubusercontent.com/60654909/80021020-983f9300-84e2-11ea-9164-5558ae87ee3d.PNG)

Как подключить scss файл к модулю admin.pug? Я добавлял его в styles.scss, но увы не помогло. 
Подскажите, что не так?

**Comment by dDenysS** [comment]
![result](https://user-images.githubusercontent.com/23075870/80098722-08e3bf80-8576-11ea-85be-ec6468819bd2.jpg)
1) нужно немного подправить layout.pug

**Comment by dDenysS** [comment]
@yurii-martyniuk удалось разобраться с проблемой?
