### ISSUE TITLE
Как адаптировать данную сборку под .sass

### ISSUE THREAD

**Issue by Vasyah** [dDenysS/gulp-template#3]
@dDenysS 
Необходимо, чтобы сборка работала и с .sass ,и с .scss файлами
пытаюсь в задаче styles и serve изменить на .+(sass|scss) , но компилируются только файлы scss
Спасибо

**Comment by dDenysS** [comment]
![image](https://user-images.githubusercontent.com/23075870/80602385-ba339b00-8a37-11ea-9f39-405836362f4b.png)
Добрый день. Странно что у вас не работает. Вы также сделали как на скрине и перезапустили сборку?
![image](https://user-images.githubusercontent.com/23075870/80602702-18607e00-8a38-11ea-839d-cfeeed0f6030.png)
Еще не забудьте здесь изменить.
