### ISSUE TITLE
Изображения

### ISSUE THREAD

**Issue by kssinitsyn** [dDenysS/gulp-template#4]
Что-то не могу понять, почему изображения не грузятся(404). Ну явно что-то с путями. Как я понимаю в src создаем папку img, ну и в разметке в src прописываем путь ./img/logo.png? В конфигах вроде ничего не вижу что мешало бы...

**Comment by dDenysS** [comment]
@kssinitsyn Добрый день. Это была ошибка в сборке. Добавил пример с картинкой,  код уже обновил.  Для стилей будет вот такой путь: **../img/logo.png**

**Comment by kssinitsyn** [comment]
Эта сборка у тебя на винде работает? У меня на маке стало ок, но на винде не инсталятся 2 плагина, и соответственно все не работает)

**Comment by kssinitsyn** [comment]
проблема в optipng и gifsicle. Как я понял проблема распространенная, еще и из-за того что в корпоративной сети незя такие пакеты выкачивать из-за сертификата. Может альтернативу посоветуешь?

**Comment by kssinitsyn** [comment]
Шрифты тоже что-то не встают)

**Comment by dDenysS** [comment]
> Эта сборка у тебя на винде работает? У меня на маке стало ок, но на винде не инсталятся 2 плагина, и соответственно все не работает)

да, на винде работает

**Comment by dDenysS** [comment]
> Шрифты тоже что-то не встают, если добавлять импортом в самом sass в файл fonts.scss

Ничего не могу сказать. Есть ссылка на репозиторий или примеры кода?

**Comment by dDenysS** [comment]
> проблема в optipng и gifsicle. Как я понял проблема распространенная, еще и из-за того что в корпоративной сети незя такие пакеты выкачивать из-за сертификата. Может альтернативу посоветуешь?

Сложно что то посоветовать, не знаю какие пакеты будут работать. Плюс не так просто найти пакеты потому что многие из них используют внутри себя выше указанные плагины
