### ISSUE TITLE
Изображения #2

### ISSUE THREAD

**Issue by Vasyah** [dDenysS/gulp-template#5]
Приветствую, подскажи, пожалуйста: Каждый раз добавляя новое изображения, приходится перезапускать gulp, для того, чтобы в папке build изображения обновились, подскажи, как это автоматизировать или может я что-то отключил в самой сборке.
Спасибо!

**Comment by dDenysS** [comment]
![image](https://user-images.githubusercontent.com/23075870/84408860-5646e980-ac15-11ea-8557-cdf01111565e.png) - файл server.js. Вот эта строка следит за изменениями картинок. Если есть возможность скиньте ссылку на репозиторий, я посмотрю в чем проблема.

**Comment by Vasyah** [comment]
https://github.com/Vasyah/LSTK.git

**Comment by dDenysS** [comment]
Добрый вечер. Добавил кэширование картинок. Не забудьте обновить код.
