### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by igorprots** [dDenysS/gulp-template#6]
Объясните пожалуйста как правильно подключить нестандартные шрифты. После добавления папки fonts в build и src, команда gulp start  папки со шрифтами в sources нету, соответственно они не подгружаются.

![image](https://user-images.githubusercontent.com/58881197/85031965-f5289400-b187-11ea-93ee-90a0d73e851d.png)

**Comment by dDenysS** [comment]
@igorprots Добрый вечер. Забыл, добавить задачу которая бы переносила шрифты. Уже исправлено.
