### ISSUE TITLE
Обнаружена ошибка команды npm в package.json -> scripts -> test

### ISSUE THREAD

**Issue by NikolayLemehov** [dDenysS/gulp-template#8]
Обнаружена ошибка команды npm в package.json -> scripts -> test:

npm test работает не полностью. Если ошибка возникает при проверке editorconfig, то не проверяют stylelint и eslint. Если ошибок editorconfig не обнаружил, а обнаружил stylelint, то на этом проверка останавливается и eslint не проверяет. Если в package.json заменить "&&" на "&", то тогда проверяет всё сразу, так как команды запускаются параллельно и завершение работы при ошибке не влияет на другие команды в списке как описано [здесь](https://www.npmjs.com/package/npm-run-all) (npm-run-all). Аналогичная задача была решена в [es6-gulp-template](https://github.com/Azune-NK/es6-gulp-template/issues/6).
[Здесь](https://github.com/dDenysS/gulp-template/pull/7) я сделал Pull requests с решением.

Ещё в двух местах есть двойной амперсанд, но там он работает.
1. В lighthouse он срабатывал, ошибка БЭМ не остановила выполнение. Но возможно другие ошибки смогут остановить, не проверял. Вопрос в том нужно ли проверять в lighthouse с ошибками.
2. В husky же необходима работа последовательного исполнения, так как при параллельном варианте комит будет сделан в любом случае, чего нам не нужо. По этому последовательное решение здесь в точку.

**Comment by dDenysS** [comment]
@NikolayLemehov Спасибо. Отличное замечание.  На счет lighthouse, там нужен двойной амперсанд потому что нужно тестировать максимально правильный код. Некоторые ошибки влияют на итоговые балы lighthouse.
