### ISSUE TITLE
Нужна ли строчка проверки html в корне src?

### ISSUE THREAD

**Issue by NikolayLemehov** [dDenysS/gulp-template#9]
Ожидается ли проверка (планируется ли нахождение html в корне src) editorconfig [эти](http://prntscr.com/te4n8y) html в корне src (в src используется только pug, а html от lighthouse не нуждается в проверке от editorconfig)?
Если короче, то нужна ли вышеописанная строчка?

**Comment by dDenysS** [comment]
@NikolayLemehov Спасибо за замечание. Да, там ошибка.  Заменил ` "src/*.html"` на `"src/pages/**/*.pug"`
